# AUTO-GENERATED by the crux release workflow.
# Source of truth: https://github.com/lowkeyliesmyth/crux/blob/main/.github/workflows/release.yml
# Do NOT edit by hand. Changes will be overwritten on the next crux release.
class Crux < Formula
  desc "DevEx and operations CLI for everyday workflows"
  homepage "https://github.com/lowkeyliesmyth/crux"
  version "0.3.4"
  license "MIT"

  on_macos do
    depends_on arch: :arm64
    on_arm do
      url "https://github.com/lowkeyliesmyth/crux/releases/download/#{version}/crux-#{version}-darwin-arm64.tar.gz"
      sha256 "488a893083a3e0d3191203d1f34188ce5e8d7ef655ebf2d4a016c686dac5ba05"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/lowkeyliesmyth/crux/releases/download/#{version}/crux-#{version}-linux-arm64.tar.gz"
      sha256 "98a66e7be057a5d56fcd744c38869c43ddf1b8e0c848a07de26be6e5d7a89124"
    end
    on_intel do
      url "https://github.com/lowkeyliesmyth/crux/releases/download/#{version}/crux-#{version}-linux-x86_64.tar.gz"
      sha256 "9efe2ac8fdc59eaac5621d6506b18f77395fd9a11e2c622c2f4329cf6cab4331"
    end
  end

  def install
    bin.install "crux"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/crux version")
  end
end
