# AUTO-GENERATED by the crux release workflow.
# Source of truth: https://github.com/lowkeyliesmyth/crux/blob/main/.github/workflows/release.yml
# Do NOT edit by hand. Changes will be overwritten on the next crux release.
class Crux < Formula
  desc "DevEx and operations CLI for everyday workflows"
  homepage "https://github.com/lowkeyliesmyth/crux"
  version "0.3.3"
  license "MIT"

  on_macos do
    depends_on arch: :arm64
    on_arm do
      url "https://github.com/lowkeyliesmyth/crux/releases/download/#{version}/crux-#{version}-darwin-arm64.tar.gz"
      sha256 "6b20eb534c101aba4b0060140d7e6ff8f273ce5e5b2014e9f2bb2fcb2bc03ec8"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/lowkeyliesmyth/crux/releases/download/#{version}/crux-#{version}-linux-arm64.tar.gz"
      sha256 "983566a7c7176c3ce7973c8d16a30d1fdd34705813a949964d2d2a5ee29f8c12"
    end
    on_intel do
      url "https://github.com/lowkeyliesmyth/crux/releases/download/#{version}/crux-#{version}-linux-x86_64.tar.gz"
      sha256 "a844c99f9bee25c290a78c9daa577830a6e8420f0489f89714acb522b50166ba"
    end
  end

  def install
    bin.install "crux"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/crux version")
  end
end
